DEAP_DATASET = "../../../../../../DEAP"
INT_RANDOM_SEED = 42
MUSIC_SAMPLE_RATE = 22050
DEAP_SAMPLE_RATE = 128
STR_CH_FIRST = 'channels_first'
STR_CH_LAST = 'channels_last'
INPUT_LENGTH = MUSIC_SAMPLE_RATE * 10
CHUNK_SIZE = 16